# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='img_source',
            field=models.CharField(default='http://epaper.gujaratimidday.com/images/no_image_thumb.gif', max_length=128),
        ),
    ]
